[mssql]
drivername = "mssql+pyodbc"
host = "localhost"
port = 1433
username = "sa"
password = "StrongPassword123!"
database = "master"
query = { driver = "ODBC Driver 17 for SQL Server", TrustServerCertificate = "yes", Encrypt = "no", "Connection Timeout" = "30" }